server:
  port: 8166
  servlet:
    context-path: /web-market-carts
utils:
  cart:
    prefix: SPRING_WEB_APP_T
integrations:
  core-service:
    url: http://localhost:8189/web-market-core/
    connect-timeout: 500
    read-timeout: 10000
    write-timeout: 5000